
import Footer from "@components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import ServerSessionProvider from "@/sessionProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ServerSessionProvider>
            <NavBar />
            <div className="min-h-screen bg-base-200">{children}</div>
            <Footer />
          </ServerSessionProvider>
      </body>
    </html>
  );
}
