version: "3.8"
services:
  frontend:
    image: frontend-image:latest
    container_name: frontend
    restart: on-failure
    build: frontend
    depends_on:
      - database
      - backend
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  backend:
    image: backend-image:latest
    container_name: backend
    restart: on-failure
    build: backend
    depends_on:
      - database
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "4006:4006"
  database:
    image: postgres:13-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cm
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - database
    ports:
      - "9090:9090"
    environment:
      PGADMIN_DEFAULT_EMAIL: sunnepazzy123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 9090  # Set the internal port to 9090

volumes:
  postgres_data:
  mongodb-data:
